kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "psqlclient" 
spec:
  runPolicy: "Serial"
  source:
    dockerfile:
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: ./Dockerfile 

