apiVersion: apps/v1
kind: Deployment
metadata:
  name: psqlclient
  labels:
    app: psqlclient
spec:
  selector:
    matchLabels:
      app: psqlclient
  replicas: 1
  template:
    metadata:
      labels:
        app: psqlclient
    spec:
      containers:
        - name: psqlclient
          image: ubi-minimal
#          command:
#            - "/bin/bash"
#            - "-c"
#            - "while true; do ls /root/buildinfo/; sleep 30; done"